package minty.ui;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.shape.Polygon;

/**
 * Displays one message from either the user or Minty.
 */
public class DialogBox extends HBox {
    private static final double AVATAR_SIZE = 58;
    private static final double MAX_MESSAGE_WIDTH = 300;

    private DialogBox(String text, Image avatar, boolean isUser) {
        Label message = new Label(text);
        message.setWrapText(true);
        message.setMaxWidth(MAX_MESSAGE_WIDTH);
        message.getStyleClass().add(isUser ? "user-message" : "minty-message");

        ImageView displayPicture = new ImageView(avatar);
        displayPicture.setFitHeight(AVATAR_SIZE);
        displayPicture.setFitWidth(AVATAR_SIZE);
        displayPicture.setPreserveRatio(true);

        setAlignment(isUser ? Pos.TOP_RIGHT : Pos.TOP_LEFT);
        setSpacing(8);
        getStyleClass().add("dialog-box");
        if (isUser) {
            getChildren().addAll(message, displayPicture);
        } else {
            // Place the tail behind the bubble so its inner edge is hidden by the label.
            Polygon tail = new Polygon(0, 0, 12, 0, 12, 12);
            tail.getStyleClass().add("minty-tail");
            tail.setTranslateX(-6);
            tail.setTranslateY(14);
            StackPane bubble = new StackPane(tail, message);
            bubble.setAlignment(Pos.TOP_LEFT);
            bubble.setMaxWidth(MAX_MESSAGE_WIDTH);
            getChildren().addAll(displayPicture, bubble);
        }
    }

    /**
     * Creates a right-aligned dialog containing a user command.
     *
     * @param text command entered by the user.
     * @param avatar image representing the user.
     * @return dialog configured for a user message.
     */
    public static DialogBox getUserDialog(String text, Image avatar) {
        return new DialogBox(text, avatar, true);
    }

    /**
     * Creates a left-aligned dialog containing Minty's response.
     *
     * @param text response generated by Minty.
     * @param avatar image representing Minty.
     * @return dialog configured for a Minty response.
     */
    public static DialogBox getMintyDialog(String text, Image avatar) {
        return new DialogBox(text, avatar, false);
    }
}
