package minty.ui;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Displays one message from either the user or Minty.
 */
public class DialogBox extends HBox {
    private static final double MAX_MESSAGE_WIDTH = 330;

    private DialogBox(String text, boolean isUser) {
        Label message = new Label(text);
        message.setWrapText(true);
        message.setMaxWidth(MAX_MESSAGE_WIDTH);
        message.getStyleClass().add(isUser ? "user-message" : "minty-message");

        setAlignment(isUser ? Pos.TOP_RIGHT : Pos.TOP_LEFT);
        getStyleClass().add("dialog-box");
        getChildren().add(message);
    }

    /**
     * Creates a right-aligned dialog containing a user command.
     *
     * @param text command entered by the user.
     * @return dialog configured for a user message.
     */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, true);
    }

    /**
     * Creates a left-aligned dialog containing Minty's response.
     *
     * @param text response generated by Minty.
     * @return dialog configured for a Minty response.
     */
    public static DialogBox getMintyDialog(String text) {
        return new DialogBox(text, false);
    }
}
